<a href="https://colab.research.google.com/github/VibhaeoM01/ML-/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##libraries- tensorflow 2.0 and keras


#flow
1. Sentences
2. One hot Representation-- index from the
3. Onhot Repre---> Embeddind Layer Keras
I
To form Embedding matrix
4. Embedding matrix

vocb_size=10000, dimension=10

In [2]:
import tensorflow as tf

In [3]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',

]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
voc_size=10000

One hot representation

In [8]:
 onehot_repr=[one_hot(words,voc_size) for words in sent]
 print(onehot_repr)

[[8255, 1045, 8512, 3614], [8255, 1045, 8512, 5629], [8255, 6518, 8512, 9995], [3242, 751, 9445, 7785, 2900], [3242, 751, 9445, 7785, 5796], [7664, 8255, 6218, 8512, 8250], [3305, 2783, 6763, 7785]]


Word Embedding Representation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
#Embeeding layer and sequential layer
#pad_sequences is used to make sure that size of sequences is same

In [10]:
import numpy as np

In [11]:
sent_length=8   #padding
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8255 1045 8512 3614]
 [   0    0    0    0 8255 1045 8512 5629]
 [   0    0    0    0 8255 6518 8512 9995]
 [   0    0    0 3242  751 9445 7785 2900]
 [   0    0    0 3242  751 9445 7785 5796]
 [   0    0    0 7664 8255 6218 8512 8250]
 [   0    0    0    0 3305 2783 6763 7785]]


In [12]:
dim=10
#dim is features

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')


In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 200ms/step
[[[ 0.01683429  0.02693205  0.04420171 -0.0310095   0.04636265
    0.02579917 -0.00723051  0.00623639  0.03767029  0.03912339]
  [ 0.01683429  0.02693205  0.04420171 -0.0310095   0.04636265
    0.02579917 -0.00723051  0.00623639  0.03767029  0.03912339]
  [ 0.01683429  0.02693205  0.04420171 -0.0310095   0.04636265
    0.02579917 -0.00723051  0.00623639  0.03767029  0.03912339]
  [ 0.01683429  0.02693205  0.04420171 -0.0310095   0.04636265
    0.02579917 -0.00723051  0.00623639  0.03767029  0.03912339]
  [-0.04062764  0.04341979 -0.01684011 -0.0024614  -0.00928838
    0.04740921 -0.01193003  0.04719973  0.04552611 -0.01064259]
  [ 0.0399419  -0.02769256 -0.03115325  0.03267971  0.00401371
   -0.00818487  0.00601064  0.01679626 -0.02951351  0.04607016]
  [ 0.00864977 -0.02016933  0.03881982  0.03952532  0.04029534
    0.01144539 -0.03202537  0.04405837  0.04822585 -0.03488878]
  [-0.01151531  0.04023602  0.04448305 -0.0400003  -0.0499

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 8255, 1045, 8512, 3614], dtype=int32)

Embedding Matrix

In [18]:
print(model.predict(embedded_docs[0]))   #ok so this is of every index of embedded_docs, like for 0 it has give whole of 10 vectors becuase we
#gave dimension of 10      vectorsmodel.add(Embedding(voc_size,10,input_length=sent_length)), so that is why every index has dim of 10 vectors

1/1 [==============================] - 0s 21ms/step
[[ 0.01683429  0.02693205  0.04420171 -0.0310095   0.04636265  0.02579917
  -0.00723051  0.00623639  0.03767029  0.03912339]
 [ 0.01683429  0.02693205  0.04420171 -0.0310095   0.04636265  0.02579917
  -0.00723051  0.00623639  0.03767029  0.03912339]
 [ 0.01683429  0.02693205  0.04420171 -0.0310095   0.04636265  0.02579917
  -0.00723051  0.00623639  0.03767029  0.03912339]
 [ 0.01683429  0.02693205  0.04420171 -0.0310095   0.04636265  0.02579917
  -0.00723051  0.00623639  0.03767029  0.03912339]
 [-0.04062764  0.04341979 -0.01684011 -0.0024614  -0.00928838  0.04740921
  -0.01193003  0.04719973  0.04552611 -0.01064259]
 [ 0.0399419  -0.02769256 -0.03115325  0.03267971  0.00401371 -0.00818487
   0.00601064  0.01679626 -0.02951351  0.04607016]
 [ 0.00864977 -0.02016933  0.03881982  0.03952532  0.04029534  0.01144539
  -0.03202537  0.04405837  0.04822585 -0.03488878]
 [-0.01151531  0.04023602  0.04448305 -0.0400003  -0.04990065  0.04306327